Set Shell zsh
Sleep 1s
Type "./demo"
Enter
Sleep 3s
Left 1
Sleep 400ms
Left 1
Sleep 400ms
Left 1
Sleep 250ms
Left 1
Sleep 250ms
Left 1
Sleep 250ms
Left 1
Sleep 250ms
Left 1
Sleep 250ms
Left 1
Sleep 400ms
Right 1
Sleep 300ms
Right 1
Sleep 300ms
Right 1
Sleep 300ms
Right 1
Sleep 400ms
Tab
Sleep 800ms
Tab
Sleep 2s
Left 1
Sleep 400ms
Left 1
Sleep 400ms
Left 1
Sleep 400ms
Tab
Sleep 1s
Right 1
Sleep 250ms
Right 1
Sleep 250ms
Right 1
Sleep 250ms
Right 1
Sleep 3s
